### ISSUE TITLE
壁紙の設定を起動するとJSエラーになる

### ISSUE THREAD

**Issue by yugeta** [yugeta/web_desktop#46]
```
background.js:33 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at get body (background.js:33:22)
    at Background.set_body (background.js:54:10)
    at new Background (background.js:17:14)
    at ContextMenu.click (context_menu.js:202:9)
    at new ContextMenu (context_menu.js:25:14)
    at Click.event (click.js:45:7)
    at new Click (click.js:6:10)
    at HTMLElement.<anonymous> (event.js:14:64)
get body @ background.js:33
set_body @ background.js:54
Background @ background.js:17
click @ context_menu.js:202
ContextMenu @ context_menu.js:25
event @ click.js:45
Click @ click.js:6
(anonymous) @ event.js:14Understand this errorAI
view.js:86 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'window_size')
    at get init_rect (view.js:86:48)
    at View.add (view.js:125:70)
    at view.js:21:14
    at new Promise (<anonymous>)
    at new View (view.js:12:20)
    at window.js:23:11
    at new Promise (<anonymous>)
    at new Window (window.js:12:20)
    at Background.window_view (background.js:41:5)
    at new Background (background.js:16:14)
```
<img width="588" alt="スクリーンショット 2024-10-29 8 34 39" src="https://github.com/user-attachments/assets/dab46ea8-c779-4ac5-a252-52f8ada7924b">

**Comment by yugeta** [comment]
window/view.jsを修正してfix
