### ISSUE TITLE
アイコンクリックでウィンドウ表示する際にJSエラーがでる。

### ISSUE THREAD

**Issue by yugeta** [yugeta/web_desktop#49]
<img width="371" alt="スクリーンショット 2024-10-30 14 46 04" src="https://github.com/user-attachments/assets/a27ece89-a625-4b0e-961e-1c5186865919">

view.js:90 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'width')
    at get init_rect (view.js:90:23)
    at View.add (view.js:125:70)
    at view.js:21:14
    at new Promise (<anonymous>)
    at new View (view.js:12:20)
    at window.js:23:11
    at new Promise (<anonymous>)
    at new Window (window.js:12:20)
    at DoubleClick.event (double_click.js:15:7)
    at new DoubleClick (double_click.js:5:10)

**Comment by yugeta** [comment]
修正済み
