### ISSUE TITLE
アイコンドラッグ移動時に、アイコンが白紙になって、JSエラーが出ている。

### ISSUE THREAD

**Issue by yugeta** [yugeta/web_desktop#50]
<img width="366" alt="スクリーンショット 2024-10-30 14 49 27" src="https://github.com/user-attachments/assets/007c6d5e-7d14-4330-bcb5-0ff2ab15cdd7">

icon.js:70 Uncaught TypeError: Cannot set property x of #<Icon> which has only a getter
    at get data (icon.js:70:14)
    at MouseUp.save_icon (mouse_up.js:41:45)
    at new MouseUp (mouse_up.js:10:12)
    at HTMLElement.<anonymous> (event.js:13:64)

**Comment by yugeta** [comment]
修正済み
